name: Kernel Build 5.15

on:
  workflow_dispatch:
    inputs:
      KERNEL_REPO:
        description: 'KERNEL_REPO'
        required: true
        default: 'https://github.com/zainarbani/kernel-5.15'
      KERNEL_BRANCH:
        description: 'KERNEL_BRANCH'
        required: true
        default: 'main'
      BUILD_SCRIPT_REPO:
        description: 'BUILD_SCRIPT_REPO'
        required: true
        default: 'https://github.com/zainarbani/kernel_build_script'
      BUILD_SCRIPT_BRANCH:
        description: 'BUILD_SCRIPT_BRANCH'
        required: true
        default: 'a54x'
      BUILD_NOTES:
        description: 'BUILD_NOTES'
        required: false
        default: 'N\A'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: buildjet-8vcpu-ubuntu-2204
    permissions:
      contents: write
    steps:

    - name: Prepare Env
      run: |
        export TZ="Asia/Jakarta"
        export DATE=$(date "+%Y%m%d-%H%M")
        echo "BUILD_DATE=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        sudo apt update  &> /dev/null
        sudo apt -y install libelf-dev dwarves &> /dev/null
        mkdir -p $GITHUB_WORKSPACE/project

    - name: Prepare Kernel
      run: |
        cd $GITHUB_WORKSPACE/project
        git clone -b ${{ github.event.inputs.KERNEL_BRANCH }} ${{ github.event.inputs.KERNEL_REPO }} linux --depth=1 &> /dev/null
        cd linux
        git clone -b ${{ github.event.inputs.BUILD_SCRIPT_BRANCH }} ${{ github.event.inputs.BUILD_SCRIPT_REPO }} kernel_build --depth=1 &> /dev/null
        echo "KERNEL_VER=$(make kernelversion)" >> $GITHUB_ENV
        echo "CLANG_VER=$(clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g')" >> $GITHUB_ENV

    - name: Building Kernel
      run: |
        cd $GITHUB_WORKSPACE/project/linux
        chmod +x kernel_build/build.sh && ./kernel_build/build.sh
        
    - name: Upload Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}/project/linux/kernel_build/Kernel_a54x.tar
          ${{ github.workspace }}/project/linux/kernel_build/Kernel_a54x.zip
        name: ${{ github.event.inputs.BUILD_SCRIPT_BRANCH }}-${{ env.BUILD_DATE }}
        tag_name: ${{ env.BUILD_DATE }}
        body: |
          Device: ${{ github.event.inputs.BUILD_SCRIPT_BRANCH }}
          Repo: ${{ github.event.inputs.KERNEL_REPO }}
          Branch: ${{ github.event.inputs.KERNEL_BRANCH }}
          Notes:\n
          ${{ github.event.inputs.BUILD_NOTES }
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Update TG
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.CHAT_ID }}
        token: ${{ secrets.BOT_TOKEN }}
        format: html
        disable_web_page_preview: true
        message: |
          <b>Kernel Update</b>

          <b>Build Date: </b>${{ env.BUILD_DATE }}
          
          <a href="https://github.com/${{ github.repository }}/releases/tag/${{ env.BUILD_DATE }}">Download</a>
          
          <a href="${{ github.event.inputs.KERNEL_REPO }}/commits/${{ github.event.inputs.KERNEL_BRANCH }}">Changelogs</a>


          <b>Device: </b>${{ github.event.inputs.BUILD_SCRIPT_BRANCH }}
          <b>Kernel Ver: </b>${{ env.KERNEL_VER }}
          <b>Clang Ver: </b>${{ env.CLANG_VER }}
          <b>Maintainer: </b>@AnotherZain
